AntiRating/AntiRating/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AntiRating.Models;
using AntiRating.Domain;
using AntiRating.Domain.Entities;
using AntiRating.Helpers;
using MvcPager;

namespace AntiRating.Controllers
{

    [Authorize]
    public class ClaimController : CommonController
    {        

        public ActionResult Index(int pageIndex = 0)
        {
            var currentProfile = GetCurrentProfile();
            if (currentProfile == null)
                return RedirectToAction("Index", "Home");

            var claims = Repository.GetAll<Claim>().Where(c => c.Creator.Id == currentProfile.Id).OrderByDescending(o=>o.CreationDate).ToPagedList(pageIndex, PageSize).ToList();
            var models = ViewModelHelper.ClaimsToNewVm(claims);

            ViewBag.ProfileInfo = new UserHelper(Repository.DbContext).GetCurrentProfileInfo();

            return View(models.ToPagedList(pageIndex, PageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            var profile = GetCurrentProfile();
            if (profile!=null)
                return View(new NewClaimModel { ProfileId = GetCurrentProfile().Id });
            return RedirectToAction("Login", "Account");
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Create(NewClaimModel model)
        {
            if (ModelState.IsValid)
            {                
                var claim= new Claim();
                claim.Name = model.Name;
                claim.ObjectType = model.ObjectType;
                claim.CreationDate = model.CreationDate != null ? model.CreationDate.Value : DateTime.Now;
                claim.CityId = model.CityId.Value;

                if (model.ObjectPhoto.FileBase != null)
                {
                    var objectPhoto = new Photo();
                    objectPhoto.Name = model.ObjectPhoto.FileBase.FileName;
                    objectPhoto.ContentType = model.ObjectPhoto.FileBase.ContentType;
                    objectPhoto.Content = new byte[model.ObjectPhoto.FileBase.ContentLength];
                    model.ObjectPhoto.FileBase.InputStream.Read(objectPhoto.Content, 0, model.ObjectPhoto.FileBase.ContentLength);
                    claim.Photo = objectPhoto;
                }

                var creatorProfile=(new UserHelper(Repository.DbContext)).GetCurrentProfile();
                claim.Creator = creatorProfile;


                var disLike = new Dislike
                {
                    Claim = claim,
                    CreationDate = claim.CreationDate,
                    CreatorProfile = creatorProfile,
                    DislikeType = DislikeType.Accusing,
                    Text = model.Text,
                    MainDislike = true,
                    Category = model.DislikeCategory
                };
                if (model.VideoReferences.Any())
                {
                    disLike.VideoReferences= new List<VideoReference>();
                    foreach (var url in model.VideoReferences)
                    {
                        var videoReference = new VideoReference();
                        videoReference.Reference = url;
                        disLike.VideoReferences.Add(videoReference);

                    }
                }

                if (model.Photos.Any())
                {
                    disLike.Photos= new List<Photo>();
                    foreach (var httpPostedFileBase in model.Photos.Where(f=>f.FileBase != null))
                    {
                        var  photo= new Photo();
                        photo.Name = httpPostedFileBase.FileBase.FileName;
                        photo.ContentType = httpPostedFileBase.FileBase.ContentType;
                        photo.Content= new byte[httpPostedFileBase.FileBase.ContentLength];
                        httpPostedFileBase.FileBase.InputStream.Read(photo.Content, 0, httpPostedFileBase.FileBase.ContentLength);
                        disLike.Photos.Add(photo);
                    }
                }

                if (model.Docs.Any())
                {
                    disLike.Docs= new List<Doc>();
                    foreach (var httpPostedFileBase in model.Docs.Where(f=>f.FileBase!=null))
                    {
                        var doc= new Doc();
                        doc.Name = httpPostedFileBase.FileBase.FileName;
                        doc.ContentType = httpPostedFileBase.FileBase.ContentType;
                        doc.Content = new byte[httpPostedFileBase.FileBase.ContentLength];
                        httpPostedFileBase.FileBase.InputStream.Read(doc.Content, 0, httpPostedFileBase.FileBase.ContentLength);
                        disLike.Docs.Add(doc);
                    }
                }
                Repository.Add(disLike);
                Repository.Add(claim);
                Repository.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var claim = Repository.GetAll<Claim>().FirstOrDefault(c => c.Id == id);

            if (claim == null)
                return RedirectToAction("Index");

            var mainDislike = claim.Dislikes.FirstOrDefault(d => d.MainDislike);

            if (mainDislike == null)
                return RedirectToAction("Index");

            var vm = new NewClaimModel
            {
                Id = claim.Id,
                Name = claim.Name,
                Text = mainDislike.Text,
                MainDislikeId = mainDislike.Id,
                ObjectType = claim.ObjectType,
                DislikeCategory = mainDislike.Category,
                CityId = claim.CityId
            };

            if (claim.Photo != null)
            {
                vm.ObjectPhoto = new FileViewModel
                {
                    Id = claim.Photo.Id,
                    Content = claim.Photo.Content,
                    ContentType = claim.Photo.ContentType,
                    Name = claim.Photo.Name
                };
            }

            if (mainDislike.Photos != null)
            {
                foreach (var photo in mainDislike.Photos.ToList())
                {
                    vm.Photos.Add(new FileViewModel
                    {
                        Id = photo.Id,
                        Content = photo.Content,
                        ContentType = photo.ContentType,
                        Name = photo.Name
                    });
                }
            }


            if (mainDislike.Docs != null)
            {
                foreach (var doc in mainDislike.Docs.ToList())
                {
                    vm.Docs.Add(new FileViewModel
                    {
                        Id = doc.Id,
                        Content = doc.Content,
                        ContentType = doc.ContentType,
                        Name = doc.Name
                    });
                }
            }


            foreach (var videoReference in mainDislike.VideoReferences.ToList())
            {
                vm.VideoReferenceModel.Add(new VideoReferenceModel
                {
                    Id = videoReference.Id,
                    Url = videoReference.Reference
                });
            }

            return View("Edit", vm);
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Edit(NewClaimModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var existClaim = Repository.GetAll<Claim>().FirstOrDefault(c=>c.Id == model.Id);

            if (existClaim == null)
                return View("Edit", model);

            using (var scope = Repository.DbContext.Database.BeginTransaction())
            {
                try
                {
                    existClaim.Name = model.Name;
                    existClaim.ObjectType = model.ObjectType;
                    existClaim.CreationDate = model.CreationDate != null ? model.CreationDate.Value : DateTime.Now;


                    if (model.ObjectPhoto.FileBase != null)
                    {
                        var objectPhoto = new Photo
                        {
                            Name = model.ObjectPhoto.FileBase.FileName,
                            ContentType = model.ObjectPhoto.FileBase.ContentType,
                            Content = new byte[model.ObjectPhoto.FileBase.ContentLength]
                        };
                        model.ObjectPhoto.FileBase.InputStream.Read(objectPhoto.Content, 0,
                            model.ObjectPhoto.FileBase.ContentLength);
                        
                        existClaim.Photo = objectPhoto;
                    }



                    var creatorProfile = (new UserHelper(Repository.DbContext)).GetCurrentProfile();
                    existClaim.Creator = creatorProfile;


                    var disLike = existClaim.Dislikes.FirstOrDefault(d => d.MainDislike);

                    if (disLike == null)
                    {
                        scope.Rollback();
                        ModelState.AddModelError("", "Ошибка серврера!");
                        return View("Edit", model);
                    }

                    disLike.Text = model.Text;                                            

                    if (model.VideoReferences.Any())
                    {                                                
                        foreach (var url in model.VideoReferences)
                        {
                            var videoReference = new VideoReference();
                            videoReference.Reference = url;
                            disLike.VideoReferences.Add(videoReference);
                        }
                    }

AntiRating/AntiRating/Controllers/ReferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AntiRating.Domain.Entities;
using AntiRating.Helpers;
using AntiRating.Models.CountriesApi;

namespace AntiRating.Controllers
{
    public class ReferenceController : CommonController
    {        
        public ActionResult GetCountries()
        {
            var res = Repository.GetAll<CountryReference>().Select(s=> new { s.Id, s.Info }).ToList();
            return Json(new {data = res, success = true }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetStates(Guid countryId)
        {
            var res = Repository.GetAll<StateReference>().Where(s=>s.CountryId == countryId).Select(s => new { s.Id, s.Info }).ToList();
            return Json(new { data = res, success = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCities(Guid stateId)
        {
            var res = Repository.GetAll<CityReference>().Where(s => s.StateId == stateId).Select(s => new { s.Id, s.Info }).ToList();
            return Json(new { data = res, success = true }, JsonRequestBehavior.AllowGet);
        }
    }
}

AntiRating/AntiRating/Views/Claim/Create.cshtml
@using AntiRating.Helpers
@model AntiRating.Models.NewClaimModel

@{
    ViewBag.Title = "Создать объявление";
}
<h2 style="color: #373737">@ViewBag.Title</h2>
<div class="blog-find-2">
    <div class="row">

        <div class="col-lg-12">
            @using (Html.BeginForm("Create", "Claim", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(m => m.ProfileId)
                @Html.AntiForgeryToken()


                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-4">
                            <label>Страна</label>
                            <div class="clearfix"></div>
                            <select id="countries-list"></select>
                        </div>
                        <div class="col-lg-4">
                            <label>Штат/область/регион</label>
                            <div class="clearfix"></div>
                            <select id="states-list"></select>
                        </div>
                        <div class="col-lg-4">
                            <label>Населенный пункт</label>
                            <div class="clearfix"></div>
                            <select id="CityId" name="CityId"></select>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div><br />

                @Html.Partial("_claimFileds")

                <div class="clearfix"></div><br />

                <div class="col-lg-12 m-bot15">
                    <input type="button" value="Добавить видеоматериал к жалобе" id="btnAddVideo"/>
                    <div class="clearfix"></div><br/>
                    <div id="video-container" class="form-group"></div>
                </div>

                <div class="clearfix"></div><br />

                <div class="col-lg-12 m-bot15">
                    <input type="button" value="Добавить фото к жалобе" id="btnAddPhoto"/>
                    <div class="clearfix"></div><br/>
                    <div id="photo-container" class="form-group"></div>
                </div>

                <div class="col-lg-12 m-bot15">
                    <input type="button" value="Приложить документ к жалобе" id="btnAddDoc" />
                    <div class="clearfix"></div><br />
                    <div id="doc-container" class="form-group"></div>
                </div>

                <div class="col-lg-12">
                    <input type="submit" value="Создать тему" class="button transition" />
                    <a href="@Url.Action("Index")" class="button transition invert">Назад</a>
                </div>
            }
        </div>
    </div>
</div>

<div class="clearfix"></div><br /><br />

@section Scripts {    
    <script type="text/javascript" src="@Url.Content("~/Scripts/ckeditor/ckeditor.js")"></script>
    <script>
        $('#my-claim').addClass("active");

        var fileCount = 0;
        var videoCount = 0;
        var docCount = 0;
        $(document).ready(function () {
            CKEDITOR.replace('Text');

            $('#btnAddVideo').on('click', function (e) {
                var blockId = 'VideoReferences[' + videoCount + ']';
                var videoTemplate = '<input type="text" name="' + blockId + '"/><br/>';
                $('#video-container').append(videoTemplate);
                videoCount = videoCount + 1;
            });

            $('#btnAddPhoto').on('click', function (e) {
                var blockId = 'Photos[' + fileCount + '].FileBase';
                var photoTemplate = '<input type="file"  accept=".jpeg,.jpg,.png,.bmp" name="' + blockId + '"/><br/>';
                $('#photo-container').append(photoTemplate);
                fileCount = fileCount + 1;
            });

            $('#btnAddDoc').on('click', function (e) {
                var blockId = 'Docs[' + docCount + '].FileBase';
                var photoTemplate = '<input type="file"  accept=".doc,.pdf,.txt" name="' + blockId + '"/><br/>';
                $('#doc-container').append(photoTemplate);
                docCount = docCount + 1;
            });
            
            $('#countries-list').on('change', function () {
                $('#states-list').val('-');
                $('#states-list').html('');
                ReloadStates($('#countries-list').val());
                $('#CityId').val('-');
                $('#CityId').html('');
                $('#states-list').select2();
                $('#CityId').select2();
            });
            
            $('#states-list').on('change', function () {
                $('#CityId').val('-');
                $('#CityId').html('');
                ReloadCities($('#states-list').val());
                $('#CityId').select2();
            });            

            $('#countries-list').select2();
            $('#states-list').select2();
            $('#CityId').select2();

            AjaxHelper.ajaxRequestJsonData('@Url.Action("GetCountries", "Reference")', null, function(res) {               
                $('#countries-list').append('<option selected value="-">-</option>');
                for (var index = 0; index < res.length; index++) {
                    var item = '<option value="' + res[index].Id + '">' + res[index].Info + '</option>';
                    $('#countries-list').append(item);
                }
            }, function() {
                alert('Что то пошло не так! сайт временно не доступен попробуйте позднее!');
            }, true);

        });
        
        function ReloadStates(countryId) {
            $('#states-list').append('<option selected value="-">-</option>');
            AjaxHelper.ajaxRequestJsonData('@Url.Action("GetStates", "Reference")', { countryId: countryId }, function (res) {
                for (var index = 0; index < res.length; index++) {
                    var item = '<option value="' + res[index].Id + '">' + res[index].Info + '</option>';
                    $('#states-list').append(item);
                }
            }, function () {
                alert('Что то пошло не так! сайт временно не доступен, попробуйте позднее!');
            }, true);
        }


        function ReloadCities(stateId) {
            $('#CityId').append('<option selected value="-">-</option>');
            AjaxHelper.ajaxRequestJsonData('@Url.Action("GetCities", "Reference")', { stateId: stateId }, function (res) {
                for (var index = 0; index < res.length; index++) {
                    var item = '<option value="' + res[index].Id + '">' + res[index].Info + '</option>';
                    $('#CityId').append(item);
                }
            }, function () {
                alert('Что то пошло не так! сайт временно не доступен, попробуйте позднее!');
            }, true);
        }

    </script>
}

AntiRating/AntiRating/Views/Claim/Edit.cshtml
@using AntiRating.Helpers
@model AntiRating.Models.NewClaimModel

@{
    ViewBag.Title = "Мои жалобы";
}
<h2 style="color: #373737">@ViewBag.Title</h2>
<div class="blog-find-2">
    <div class="row">
        <div class="col-lg-12">
            @using (Html.BeginForm("Edit", "Claim", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(m=>m.Id)
                @Html.HiddenFor(m => m.ProfileId)
                @Html.HiddenFor(m => m.CityId)
                @Html.AntiForgeryToken()

                @Html.Partial("_claimFileds")

                <div class="clearfix"></div><br/>

                <div class="col-lg-12">
                    @if (Model.VideoReferenceModel.Any())
                    {
                        foreach (var videoReference in Model.VideoReferenceModel)
                        {                            
                            var videiId = Guid.NewGuid();                            
                            <div class="video-prof m-bot15 linear">
                                <video id="@videiId" width="565" height="360" preload="none">
                                    <source type="video/youtube" src="@videoReference.Url"/>
                                </video>
                                <a href="@Url.Action("DeleteVideoFromClaim", "Claim", new RouteValueDictionary {{"videoId", videoReference.Id}, {"claimId", Model.Id}})" class="delete-photo-prof button transition invert"><i class="fa fa-close"></i></a>
                            </div>
                            <script>
                                $(document).ready(function () {
                                    var players = new MediaElementPlayer('#@videiId');
                                });
                            </script>
                        }
                        <hr/>
                    }
                </div>

                <div class="clearfix"></div><br />

                <div class="col-lg-12 m-bot15">
                    <input type="button" value="Добавить видеоматериал к жалобе" id="btnAddVideo"/>
                    <div class="clearfix"></div><br/>
                    <div id="video-container" class="form-group"></div>
                </div>

                <div class="clearfix"></div><br />

                <div class="col-lg-12">
                    @if (Model.Photos.Any())
                    {
                        foreach (var foto in Model.Photos)
                        {
                            <div class="photo-prof m-bot15 linear">
                                @Html.ShowImage(foto.Id.Value)
                                <a href="@Url.Action("DeleteFileFromClaim", "Claim", new RouteValueDictionary {{"photoId", foto.Id}, {"claimId", Model.Id} })" class="delete-photo-prof button transition invert"><i class="fa fa-close"></i></a>
                            </div>
                        }
                        <hr />
                    }
                </div>                

                <div class="clearfix"></div><br />

                <div class="col-lg-12 m-bot15">
                    <input type="button" value="Добавить фото к жалобе" id="btnAddPhoto" />
                    <div class="clearfix"></div><br />
                    <div id="photo-container" class="form-group"></div>
                </div>

                <div class="col-lg-12">
                    @if (Model.Docs.Any())
                    {
                        foreach (var doc in Model.Docs)
                        {
                            <div class="photo-prof m-bot15 linear">
                                @Html.ActionLink(doc.Name, "GetDocument", new { docId = doc.Id })
                                <a href="@Url.Action("DeleteDocumentFromClaim", "Claim", new RouteValueDictionary {{"docId", doc.Id}, {"claimId", Model.Id}})" class="delete-doc-prof button transition invert"><i class="fa fa-close"></i></a>
                                <br/>
                                <br />
                            </div>
                        }
                        <hr />
                    }
                </div>

                <div class="col-lg-12 m-bot15">
                    <input type="button" value="Приложить документ к жалобе" id="btnAddDoc" />
                    <div class="clearfix"></div><br />
                    <div id="doc-container" class="form-group"></div>
                </div>

                <div class="col-lg-12 m-bot15">
                    <input type="submit" value="Сохранить изменения" class="button transition"/>
                    <a href="@Url.Action("Index")" class="button transition invert">Назад</a>
                </div>



            }
        </div>
    </div>
</div>



<div class="clearfix"></div><br /><br />

@section scripts
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/ckeditor/ckeditor.js")"></script>
    <script>
        $('#my-claim').addClass("active");

        var fileCount = 0;
        var videoCount = 0;
        var docCount = 0;
        $(document).ready(function() {
            CKEDITOR.replace('Text');
           

            $('#btnAddVideo').on('click', function (e) {
                var blockId = 'VideoReferences[' + videoCount + ']';
                var videoTemplate = '<input type="text" name="' + blockId + '"/><br/>';
                $('#video-container').append(videoTemplate);
                videoCount = videoCount + 1;
            });
            

            $('#btnAddPhoto').on('click', function(e) {
                var blockId2 = 'Photos[' + fileCount + '].FileBase';
                var photoTemplate = '<input type="file"   accept=".jpeg,.jpg,.png,.bmp" name="' + blockId2 + '"/><br/>';
                $('#photo-container').append(photoTemplate);
                fileCount = fileCount + 1;
            });

            
            $('#btnAddDoc').on('click', function (e) {
                var blockId1 = 'Docs[' + docCount + '].FileBase';
                var docTemplate = '<input type="file"  accept=".doc,.pdf,.txt" name="' + blockId1 + '"/><br/>';
                $('#doc-container').append(docTemplate);
                docCount = docCount + 1;
            });
        });
    </script>
}

AntiRating/AntiRating/Views/Claim/Index.cshtml
@using AntiRating.Helpers
@using AntiRating.Models
@using MvcPager
@model IPagedList<NewClaimModel>

@{
    Layout = "~/Views/Shared/_profileLayout.cshtml";
    var profileInfo = (ProfileModel)ViewBag.ProfileInfo;
}

<div class="prof-fl">
    <h4>Профиль</h4>
    <p>
        Логин: <strong>@profileInfo.Login</strong>
    </p>
    <p>
        Имя: <strong>@profileInfo.FirstName</strong>
    </p>
    <p>
        Фамилия: <strong>@profileInfo.SecondName</strong>
    </p>
    <p>
        e-mail: <strong>@profileInfo.Email</strong>
    </p>
    <p>
        почтовый ящик показывать: @Html.CheckBox("EmailVisible", profileInfo.EmailVisible, new { @disabled = "disabled" })
    </p>
    <div class="img-ctr">
        <img src="../../Images/105516_1000.png" />
    </div>
</div>


@if (profileInfo.BonusDislikeCount >= 50)
{
    <div class="prof-fl">
        <h4>Бонусы профиля</h4>
        @if (profileInfo.BonusDislikeCount < 100)
        {
            <div class="img-dzl">
                <img src="../../Images/50 медь.png"/>
                <p>50 дизлайков</p>
            </div>
        }
        @if (profileInfo.BonusDislikeCount >= 100 && profileInfo.BonusDislikeCount < 1000)
        {
            <div class="img-dzl">
                <img src="../../Images/100 mon.png"/>
                <p>100 дизлайков</p>
            </div>
        }
        @if (profileInfo.BonusDislikeCount >= 1000 && profileInfo.BonusDislikeCount < 5000)
        {
            <div class="img-dzl">
                <img src="../../Images/1000 mon.png"/>
                <p>1000 дизлайков</p>
            </div>
        }       
        <div class="adv-gfl">
            реклама
        </div>


    </div>
}
else
{
    <div class="prof-fl">
        <h4>Получите бонусы профиля</h4>
        
            <div class="img-dzl">
                <img src="../../Images/50 медь.png" />
                <p>50 дизлайков</p>
            </div>
        
            <div class="img-dzl">
                <img src="../../Images/100 mon.png" />
                <p>100 дизлайков</p>
            </div>
        
            <div class="img-dzl">
                <img src="../../Images/1000 mon.png" />
                <p>1000 дизлайков</p>
            </div>                   
@*

        <div class="adv-gfl">
            реклама
        </div>
*@


    </div>
}

<div class="themees">
    <div>
        @if (Model.Any())
        {
            <ul>
                @foreach (var claim in Model)
                {
                    <li class="herota">
                        <div class="immmg">
                            @if (claim.ObjectPhoto != null && claim.ObjectPhoto.Id.HasValue)
                            {
                                @Html.ShowImage(claim.ObjectPhoto.Id.Value)
                            }
                            else
                            {
                                <img src="~/Images/nophoto_03.gif"/>
                            }
                            <div class="level"><i class="fa fa-user-secret"></i> @claim.ObjectType.Description()</div>
                            <div class="edit"><a href="@Url.Action("Edit", "Claim", new {id = claim.Id})">Редактировать</a></div>
                        </div>
                        <div class="top">
                            <div class="name-b">@claim.Name</div>
                            <div class="country"><i class="fa fa-calendar"></i> @claim.CreationDate.Value.ToString("f")</div>
                            <div class="prvws"><strong>Просмотров:</strong> @claim.ViewCount</div>
                        </div>

                        <div class="centr">
                            @Html.Raw(claim.Text)
                        </div>
                        <div class="clearfix"></div>
                    </li>
                }
            </ul>
        }
        else
        {
            <p>У вас пока нет ни одного объявления.</p>
        }
    </div>

    <div class="pager m-top30">
        @Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount, Url.Action("Index", "Claim", new RouteValueDictionary { { "pageIndex", Model.PageNumber } }))
    </div>
</div>

AntiRating/AntiRating/Views/Claim/Read.cshtml
@model AntiRating.Models.ClaimModel
@{
    ViewBag.Title = "Read";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@functions {
    private int i = 1;
} 

<h2>Read</h2>


@Html.HiddenFor(m => m.Id)
@Html.HiddenFor(m => m.ProfileId)
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Просмотр жалобы</h4>
    <hr />

    @Model.Name
    @if ( Model.ObjectPhoto != null)
    {
        var base64 = Convert.ToBase64String(Model.ObjectPhoto.Content);
        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        <img src="@imgSrc" height="200" />
    }

    @foreach (var dislikeModel in Model.Dislikes)
    {
        <div>
            @dislikeModel.CreationDate.ToString("YYYY-MM-DD hh-mm")
        </div>
        var str = "текст дизлайка" + @i;
        <div>@str @dislikeModel.Text</div>
        @Html.ActionLink("Посмотреть", "Read", "Dislike", new { id = @dislikeModel.Id }, null);
        i = i + 1;
        <br />
    }
</div>

AntiRating/AntiRating/Views/Claim/_claimFileds.cshtml
@using AntiRating.Helpers
@model AntiRating.Models.NewClaimModel

@{
    Layout = null;
}

<div class="col-lg-12 m-bot15">
    <div class="row">
        <div class="col-lg-4">
            @Html.LabelFor(model => model.ObjectType)
            <div class="clearfix"></div>
            @Html.FromEnumDropDownListFor(m => m.ObjectType, new { @class = "drop-downlist" })
            @Html.ValidationMessageFor(model => model.ObjectType, "", new { @class = "text-danger" })
        </div>
        <div class="col-lg-4">
            @Html.LabelFor(model => model.DislikeCategory)
            <div class="clearfix"></div>
            @Html.FromEnumDropDownListFor(m => m.DislikeCategory, new { @class = "drop-downlist" })
            @Html.ValidationMessageFor(model => model.DislikeCategory, "", new { @class = "text-danger" })
        </div>
        <div class="col-lg-4">
            @Model.Region
            @Html.LabelFor(model => model.Name)
            <div class="clearfix"></div>
            @Html.TextBoxFor(m => m.Name, new { @class = "text-box" })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

<div class="col-lg-12 m-bot15">
    @Html.LabelFor(model => model.ObjectPhoto )
    <div class="clearfix"></div>
    @if (Model.ObjectPhoto!= null && Model.ObjectPhoto.Id.HasValue)
    {
        <div class="photo-prof">
            @Html.ShowImage(Model.ObjectPhoto.Id.Value)
        </div>
                @Html.TextBoxFor(m => m.ObjectPhoto.FileBase, new { @type = "file" })
    }
    else
    {
        @Html.TextBoxFor(m => m.ObjectPhoto.FileBase, new { @type = "file" })
    }
    @Html.ValidationMessageFor(model => model.ObjectPhoto, "", new { @class = "text-danger" })
</div>

<div class="col-lg-12">
    @Html.LabelFor(model => model.Text)
    <div class="clearfix"></div>
    @Html.TextAreaFor(m => m.Text)
    @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
</div>