AntiRating/AntiRating/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AntiRating.Models;
using AntiRating.Domain;
using AntiRating.Domain.Entities;
using AntiRating.Helpers;
using MvcPager;

namespace AntiRating.Controllers
{

    [Authorize]
    public class ClaimController : CommonController
    {        

        public ActionResult Index(int pageIndex = 0)
        {
            var currentProfile = GetCurrentProfile();
            if (currentProfile == null)
                return RedirectToAction("Index", "Home");

            var claims = Repository.GetAll<Claim>().Where(c => c.Creator.Id == currentProfile.Id).OrderByDescending(o=>o.CreationDate).ToPagedList(pageIndex, PageSize).ToList();
            var models = ViewModelHelper.ClaimsToNewVm(claims);

            ViewBag.ProfileInfo = new UserHelper(Repository.DbContext).GetCurrentProfileInfo();

            return View(models.ToPagedList(pageIndex, PageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            var profile = GetCurrentProfile();
            if (profile!=null)
                return View(new NewClaimModel { ProfileId = GetCurrentProfile().Id });
            return RedirectToAction("Login", "Account");
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Create(NewClaimModel model)
        {
            if (ModelState.IsValid)
            {                
                var claim= new Claim();
                claim.Name = model.Name;
                claim.ObjectType = model.ObjectType;
                claim.CreationDate = model.CreationDate != null ? model.CreationDate.Value : DateTime.Now;
                claim.CityId = model.CityId.Value;

                if (model.ObjectPhoto.FileBase != null)
                {
                    var objectPhoto = new Photo();
                    objectPhoto.Name = model.ObjectPhoto.FileBase.FileName;
                    objectPhoto.ContentType = model.ObjectPhoto.FileBase.ContentType;
                    objectPhoto.Content = new byte[model.ObjectPhoto.FileBase.ContentLength];
                    model.ObjectPhoto.FileBase.InputStream.Read(objectPhoto.Content, 0, model.ObjectPhoto.FileBase.ContentLength);
                    claim.Photo = objectPhoto;
                }

                var creatorProfile=(new UserHelper(Repository.DbContext)).GetCurrentProfile();
                claim.Creator = creatorProfile;


                var disLike = new Dislike
                {
                    Claim = claim,
                    CreationDate = claim.CreationDate,
                    CreatorProfile = creatorProfile,
                    DislikeType = DislikeType.Accusing,
                    Text = model.Text,
                    MainDislike = true,
                    Category = model.DislikeCategory
                };
                if (model.VideoReferences.Any())
                {
                    disLike.VideoReferences= new List<VideoReference>();
                    foreach (var url in model.VideoReferences)
                    {
                        var videoReference = new VideoReference();
                        videoReference.Reference = url;
                        disLike.VideoReferences.Add(videoReference);

                    }
                }

                if (model.Photos.Any())
                {
                    disLike.Photos= new List<Photo>();
                    foreach (var httpPostedFileBase in model.Photos.Where(f=>f.FileBase != null))
                    {
                        var  photo= new Photo();
                        photo.Name = httpPostedFileBase.FileBase.FileName;
                        photo.ContentType = httpPostedFileBase.FileBase.ContentType;
                        photo.Content= new byte[httpPostedFileBase.FileBase.ContentLength];
                        httpPostedFileBase.FileBase.InputStream.Read(photo.Content, 0, httpPostedFileBase.FileBase.ContentLength);
                        disLike.Photos.Add(photo);
                    }
                }

                if (model.Docs.Any())
                {
                    disLike.Docs= new List<Doc>();
                    foreach (var httpPostedFileBase in model.Docs.Where(f=>f.FileBase!=null))
                    {
                        var doc= new Doc();
                        doc.Name = httpPostedFileBase.FileBase.FileName;
                        doc.ContentType = httpPostedFileBase.FileBase.ContentType;
                        doc.Content = new byte[httpPostedFileBase.FileBase.ContentLength];
                        httpPostedFileBase.FileBase.InputStream.Read(doc.Content, 0, httpPostedFileBase.FileBase.ContentLength);
                        disLike.Docs.Add(doc);
                    }
                }
                Repository.Add(disLike);
                Repository.Add(claim);
                Repository.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var claim = Repository.GetAll<Claim>().FirstOrDefault(c => c.Id == id);

            if (claim == null)
                return RedirectToAction("Index");

            var mainDislike = claim.Dislikes.FirstOrDefault(d => d.MainDislike);

            if (mainDislike == null)
                return RedirectToAction("Index");

            var vm = new NewClaimModel
            {
                Id = claim.Id,
                Name = claim.Name,
                Text = mainDislike.Text,
                MainDislikeId = mainDislike.Id,
                ObjectType = claim.ObjectType,
                DislikeCategory = mainDislike.Category,
                CityId = claim.CityId
            };

            if (claim.Photo != null)
            {
                vm.ObjectPhoto = new FileViewModel
                {
                    Id = claim.Photo.Id,
                    Content = claim.Photo.Content,
                    ContentType = claim.Photo.ContentType,
                    Name = claim.Photo.Name
                };
            }

            if (mainDislike.Photos != null)
            {
                foreach (var photo in mainDislike.Photos.ToList())
                {
                    vm.Photos.Add(new FileViewModel
                    {
                        Id = photo.Id,
                        Content = photo.Content,
                        ContentType = photo.ContentType,
                        Name = photo.Name
                    });
                }
            }


            if (mainDislike.Docs != null)
            {
                foreach (var doc in mainDislike.Docs.ToList())
                {
                    vm.Docs.Add(new FileViewModel
                    {
                        Id = doc.Id,
                        Content = doc.Content,
                        ContentType = doc.ContentType,
                        Name = doc.Name
                    });
                }
            }


            foreach (var videoReference in mainDislike.VideoReferences.ToList())
            {
                vm.VideoReferenceModel.Add(new VideoReferenceModel
                {
                    Id = videoReference.Id,
                    Url = videoReference.Reference
                });
            }

            return View("Edit", vm);
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Edit(NewClaimModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var existClaim = Repository.GetAll<Claim>().FirstOrDefault(c=>c.Id == model.Id);

            if (existClaim == null)
                return View("Edit", model);

            using (var scope = Repository.DbContext.Database.BeginTransaction())
            {
                try
                {
                    existClaim.Name = model.Name;
                    existClaim.ObjectType = model.ObjectType;
                    existClaim.CreationDate = model.CreationDate != null ? model.CreationDate.Value : DateTime.Now;


                    if (model.ObjectPhoto.FileBase != null)
                    {
                        var objectPhoto = new Photo
                        {
                            Name = model.ObjectPhoto.FileBase.FileName,
                            ContentType = model.ObjectPhoto.FileBase.ContentType,
                            Content = new byte[model.ObjectPhoto.FileBase.ContentLength]
                        };
                        model.ObjectPhoto.FileBase.InputStream.Read(objectPhoto.Content, 0,
                            model.ObjectPhoto.FileBase.ContentLength);
                        
                        existClaim.Photo = objectPhoto;
                    }



                    var creatorProfile = (new UserHelper(Repository.DbContext)).GetCurrentProfile();
                    existClaim.Creator = creatorProfile;


                    var disLike = existClaim.Dislikes.FirstOrDefault(d => d.MainDislike);

                    if (disLike == null)
                    {
                        scope.Rollback();
                        ModelState.AddModelError("", "Ошибка серврера!");
                        return View("Edit", model);
                    }

                    disLike.Text = model.Text;                                            

                    if (model.VideoReferences.Any())
                    {                                                
                        foreach (var url in model.VideoReferences)
                        {
                            var videoReference = new VideoReference();
                            videoReference.Reference = url;
                            disLike.VideoReferences.Add(videoReference);
                        }
                    }

AntiRating/AntiRating/Controllers/ReferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AntiRating.Domain.Entities;
using AntiRating.Helpers;
using AntiRating.Models.CountriesApi;

namespace AntiRating.Controllers
{
    public class ReferenceController : CommonController
    {        
        public ActionResult GetCountries()
        {
            var res = Repository.GetAll<CountryReference>().Select(s=> new { s.Id, s.Info }).ToList();
            return Json(new {data = res, success = true }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetStates(Guid countryId)
        {
            var res = Repository.GetAll<StateReference>().Where(s=>s.CountryId == countryId).Select(s => new { s.Id, s.Info }).ToList();
            return Json(new { data = res, success = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCities(Guid stateId)
        {
            var res = Repository.GetAll<CityReference>().Where(s => s.StateId == stateId).Select(s => new { s.Id, s.Info }).ToList();
            return Json(new { data = res, success = true }, JsonRequestBehavior.AllowGet);
        }
    }
}

AntiRating/AntiRating/Controllers/UserDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AntiRating.Domain.Entities;
using AntiRating.Models;

namespace AntiRating.Controllers
{

    [Authorize]
    public class UserDataController : CommonController
    {
        public ActionResult Index()
        {            
            return View(new UserHelper(Repository.DbContext).GetCurrentProfileInfo());
        }

        [HttpPost]
        public ActionResult Save(ProfileModel profileModel)
        {
            if (ModelState.IsValid)
            {
                var profileEntity = GetCurrentProfile();
                if (profileEntity != null)
                {
                    profileEntity.Email = profileModel.Email;
                    profileEntity.EmailVisible = profileModel.EmailVisible;
                    profileEntity.FirstName = profileModel.FirstName;
                    profileEntity.Login = profileModel.Login;
                    profileEntity.SecondName = profileModel.SecondName;

                    if (profileModel.Photo.FileBase != null)
                    {
                        var objectPhoto = new Photo
                        {
                            Name = profileModel.Photo.FileBase.FileName,
                            ContentType = profileModel.Photo.FileBase.ContentType,
                            Content = new byte[profileModel.Photo.FileBase.ContentLength]
                        };
                        profileModel.Photo.FileBase.InputStream.Read(objectPhoto.Content, 0,
                            profileModel.Photo.FileBase.ContentLength);

                        profileEntity.Photo = objectPhoto;
                    }

                    Repository.Update(profileEntity);
                    Repository.SaveChanges();
                    return RedirectToAction("Index", "Claim");

                }

            }
            return RedirectToAction("Index");
        }


    }
}

AntiRating/AntiRating/Views/Shared/AccessOwnerDenied.cshtml
@{
    ViewBag.Title = "Системное сообщение";
}

<div class="wapper">
    <div class="mainnavigation">
        <i class="icon-users ic2 fl-l"></i>
        <span class="categories">@ViewBag.Title</span>
    </div>
    <div class="clearfix"></div>
    <div class="group-index-menu fs20">
        <p>Вы можете производить операции только со своими объектами.</p>
        <div class="clearfix"></div>
    </div>
</div>

AntiRating/AntiRating/Views/Shared/Ready.cshtml
@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ready</h2>

AntiRating/AntiRating/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    <link href="~/Content/main.css" rel="stylesheet" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/Helpers")
</head>
<body>
    @Html.Partial("_disklimer")
    @RenderBody()
    @RenderSection("scripts", required: false)
</body>
</html>

AntiRating/AntiRating/Views/Shared/_Layout.cshtml
@{
    Layout = "_commonLayout.cshtml";
}
@Html.Partial("_disklimer")

<div class="wrapper">
    <ul class="top-header-menu flex-container">
        <li>@Html.ActionLink("Неприязнь", "TopDistaste", "Home")</li>
        <li>@Html.ActionLink("Неприязнь", "TopDistaste", "Home")</li>
        <li>@Html.ActionLink("Воры", "TopThief", "Home")</li>
        <li>@Html.ActionLink("Обманщики", "TopDeceivers", "Home")</li>
        <li>@Html.ActionLink("Мошенники", "TopFraudster", "Home")</li>
        <li>@Html.ActionLink("Взяточники", "TopBribetaker", "Home")</li>
        <li>@Html.ActionLink("Алименты", "TopAlimony", "Home")</li>
        <li>@Html.ActionLink("Измена", "TopInfidelity", "Home")</li>
        <li>@Html.ActionLink("Клевета", "TopSlander", "Home")</li>
        <li>@Html.ActionLink("Брачные аферисты", "TopMarriageSwindler", "Home")</li>
       <li>@Html.ActionLink("Недобросовестные работодатели", "TopUnscrupulousEmployers", "Home")</li>
        <li>@Html.ActionLink("Недобросовестные работники", "TopUnscrupulousEmployees", "Home")</li>
        <li>@Html.ActionLink("Топы", "Index", "Home")</li>
        @*<li>@Html.ActionLink("Недобросовестные работники", "TopUnscrupulousEmployees", "Home")</li>*@        
    </ul>
    <div class="content-main-wrapper clearfix">
        <div class="left-menu-account">
            @Html.Partial("_loginPartial")
            <div class="m-top15 advert-block">
                @Html.Partial("_advertBlock")
            </div>
        </div>
       
            @RenderBody()
        
        @RenderSection("scripts", required: false)
        <!--<div class="clearfix"></div>-->
    </div>
     <div class="footer">
        <p>Организаторы сайта не принимают на себя никаких гарантийных обязательств в отношении публикаций пользователей и не несут ответственности за любой прямой или косвенный ущерб и упущенную выгоду, даже если это стало результатом использования или невозможности использования сайтом.</p>
        <p class="text-center">&copy; @DateTime.Now.Year - My site</p>
    </div>
</div>

AntiRating/AntiRating/Views/Shared/_banner.cshtml
<div class="banner">
    <div class="position-center">
        <div class="col-lg-12">
            <div class="row">
                <div class="container-banner">
                    <h2>Вам необходимо<span> войти в систему!</span></h2>
                    <p>Как стало известно критики сетуют, что «Отряд самоубийц» получился попросту бестолковым, и пророчат ему провал в прокате. Издания Variety, The Playlist и EW сравнили новую картину с фильмом «Бэтмен против Супермена: На заре справедливости», которая получила всего 4,4 балла от 50 экспертов из 10 возможных по версии Metacritic.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>

AntiRating/AntiRating/Views/Shared/_commonLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Антирейтинг</title>

    <link href="~/Content/main.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/Helpers")

</head>
<body>
    @RenderBody()    
</body>
</html>

AntiRating/AntiRating/Views/Shared/_disklimer.cshtml
<div id="disklimer" class="hide">
    <div class="header">Дисклеймер</div>
    <p>Портал не несет ответственности за содержание авторских материалов и не предоставляет гарантий в связи с публикацией фактов, данных, результатов и другой информации.</p>
    <p>
        Данный проект является продуктом свободы слова и не подвержен влиянию третьих лиц (запугивание, шантаж и т.д.).
        Сайт гарантирует владельцам профилей что их права будут отстаиваться, несмотря на давление извне.
        Беспрепятственно удалить дизлайк может только его автор, указавший e-mail при заполнении.
        Мы никому не предоставляем информацию о профилях посетителей нашего сайта (почту, Mac и IP адрес, другую информацию).
        Мы доверяем всем авторам, оставившим у нас свои отзывы. Если вы с чем-то не согласны, то можете
        опровергнуть дизлайк, добавив комментарий к нему.
        Администрация портала не несет никакой ответственности за размещенные на нем дизлайки, однако всегда готова к
        рассмотрению неадекватных публикаций.
        Можно использовать информацию с портала в своих целях. Обязательное условие – наличие ссылки на источник
        информации следующего вида: в интернете (гиперссылка) (ссылка должна быть прямой, использование редиректов запрещено),
        в печатных изданиях – "По материалам портала obereg.com
    </p>
    <p>
        Мы приветствуем всех неравнодушных! Кто бы вы не были - всем посетителям всегда здесь будут рады.
        Мы собираем дизлайки и отзывы о негативных людях в вашей жизни и предупреждаем других о ваших ошибках.
        Поделись своим бесценным опытом , помоги другим сохранить справедливость.
        Расскажите о нашем проекте своим родственникам, друзьям и знакомым.
    </p>
    <p class="text-center">
        <button id="okay-disklimer" class="btn btn-success">Согласен, вхожу</button>
        <button id="fuckyou-disklimer" class="btn btn-success">Не согласен, покидаю</button>
    </p>

</div>

<script type="text/javascript">
    $(document).ready(function() {
        var disklimer = $.cookie("disklimer");
        if (disklimer == null) {
            $("#disklimer").removeClass("hide");
        }

        $("#okay-disklimer").click(function() {
            $("#disklimer").addClass("hide");
            $.cookie("disklimer", "OK", { expires: 7, path: "/" });
        });

        $("#fuckyou-disklimer").click(function() {
            window.close();
        });
    });
</script>

AntiRating/AntiRating/Views/Shared/_mainSearchContainer .cshtml
@using AntiRating.Domain
@using AntiRating.Helpers

<div class="search-block clearfix">
    @using (Html.BeginForm("Serarch", "Home"))
    {         
        <div class="col-lg-12 homePage-search-col">
            <div class="row homePage-search-row">
                @if (ViewBag.DislikeCategory != null)
                {
                    @Html.Hidden("DislikeCategory", ((DislikeCategory) ViewBag.DislikeCategory).ToString())
                }
                else
                {
                    <div class="col-lg-8 m-bot15 m-top30 homePage-search-reason">
                        <label for="DislikeCategory">Причина</label>
                        <div class="clearfix"></div>
                        @Html.FromEnumDropDownList(typeof(DislikeCategory), "DislikeCategory")
                    </div>
                }
                <div class="col-lg-8 m-bot15 m-top30 homePage-search-nameBad">
                    <div class="clearfix"></div>
                    <label for="">&nbsp;</label>
                    <input id="filterName" name="filterName" type="text" class="form-control" placeholder="Имя нехорошего человека" />
                </div>
                <!--image Sense
                <div class="col-lg-4 m-bot15">
                    <img src="../../Images/105516_1000.png" style="width: 100%; height: 70px; margin-top: 5px;"/>
                </div>
                -->
                <div class="col-lg-4 m-bot15 homePage-search-state-sel">
                    <label for="filterCountry">Страна</label>
                    <div class="clearfix"></div>
                    <select id="filterCountry" name="filterCountry"></select>
                </div>
                <div class="col-lg-4 m-bot15 homePage-search-state-sel">
                    <label for="filterState">Штат/область/регион</label>
                    <div class="clearfix"></div>
                    <select id="filterState" name="filterState" placeholder="-- Все --"></select>
                </div>
                <div class="col-lg-4 m-bot15 homePage-search-state-sel">
                    <label for="filterCity">Населенный пункт</label>
                    <div class="clearfix"></div>
                    <select id="filterCity" name="filterCity"></select>
                </div>

                <div class="col-lg-12 m-bot15 homePage-search-submit">
                    <input type="submit" value="Найти" class="button transition"/>
                </div>
        </div>
        </div>
    }
</div>
<script>
        $(document).ready(function() {
            $('#filterCountry').on('change', function() {
                $('#filterState').val('-');
                $('#filterState').html('');
                ReloadStates($('#filterCountry').val());
                $('#filterCity').val('-');
                $('#filterCity').html('');
                $('#filterState').select2();
                $('#filterCity').select2();
            });

            $('#filterState').on('change', function() {
                $('#filterCity').val('-');
                $('#filterCity').html('');
                ReloadCities($('#filterState').val());
                $('#filterCity').select2();
            });

            $('#filterCountry').select2();
            $('#filterState').select2();
            $('#filterCity').select2();

            if ($('#DislikeCategory') && $('#DislikeCategory').length > 0)
                $('#DislikeCategory').select2();

            AjaxHelper.ajaxRequestJsonData('@Url.Action("GetCountries", "Reference")', null, function(res) {
                $('#filterCountry').append('<option selected value="-">-</option>');
                for (var index = 0; index < res.length; index++) {
                    var item = '<option value="' + res[index].Id + '">' + res[index].Info + '</option>';
                    $('#filterCountry').append(item);
                }
            }, function() {
                alert('Что то пошло не так! сайт временно не доступен попробуйте позднее!');
            }, true);

        });

        function ReloadStates(countryId) {
            $('#filterState').append('<option selected value="-">-</option>');
            AjaxHelper.ajaxRequestJsonData('@Url.Action("GetStates", "Reference")', { countryId: countryId }, function(res) {
                for (var index = 0; index < res.length; index++) {
                    var item = '<option value="' + res[index].Id + '">' + res[index].Info + '</option>';
                    $('#filterState').append(item);
                }
            }, function() {
                alert('Что то пошло не так! сайт временно не доступен попробуйте позднее!');
            }, true);
        }


        function ReloadCities(stateId) {
            $('#filterCity').append('<option selected value="-">-</option>');
            AjaxHelper.ajaxRequestJsonData('@Url.Action("GetCities", "Reference")', { stateId: stateId }, function(res) {
                for (var index = 0; index < res.length; index++) {
                    var item = '<option value="' + res[index].Id + '">' + res[index].Info + '</option>';
                    $('#filterCity').append(item);
                }
            }, function() {
                alert('Что то пошло не так! сайт временно не доступен попробуйте позднее!');
            }, true);
        }
</script>

AntiRating/AntiRating/Views/Shared/_profileLayout.cshtml
@{
    Layout = "_commonLayout.cshtml";
}

<div class="head-reg text-right">
    <ul class="calaim_ul">
        <li>@Html.ActionLink("Добавить объявление", "Create", "Claim")</li>
        <li>@Html.ActionLink("Рейтинги", "Index", "Home")</li>
        <li>@Html.ActionLink("Настройки профиля", "Index", "UserData")</li>
        <li>@Html.ActionLink("Выход", "LogOff", "Account")</li>
    </ul>
</div>


<div class="wrapper">
    <div class="gr-bl">
        <a href="@Url.Action("Index", "Claim")">Профиль</a>
        <a href="@Url.Action("Index", "UserData")">Редактировать профиль</a>
        <a href="@Url.Action("ChangePassword", "Account")">Сменить пароль</a>
        <a href="@Url.Action("Create", "Claim")">Добавить объявление</a>  
    </div>    
    @RenderBody()
   
</div>

AntiRating/AntiRating/Views/Shared/_searchContainer.cshtml
@using AntiRating.Domain
@using AntiRating.Helpers

<div class="search-block2 thief-search">
    @using (Html.BeginForm("Serarch", "Home"))
    {         
        <div class="col-lg-12">
            <div class="row">
                @if (ViewBag.DislikeCategory != null)
                {
                    @Html.Hidden("DislikeCategory", ((DislikeCategory) ViewBag.DislikeCategory).ToString())
                }
                else
                {
                    <div class="col-lg-8 m-bot15 m-top30">
                        <label for="DislikeCategory">Причина</label>
                        <div class="clearfix"></div>
                        @Html.FromEnumDropDownList(typeof(DislikeCategory), "DislikeCategory")
                    </div>
                }
                <div class="col-lg-8 m-bot15 m-top30">
                    <div class="clearfix"></div>
                    <label for="">&nbsp;</label>
                    <input id="filterName" name="filterName" type="text" class="form-control" placeholder="Имя нехорошего человека" />
                </div>
                <!--<div class="col-lg-4 m-bot15">
                    <img src="../../Images/105516_1000.png" style="width: 100%; height: 70px; margin-top: 5px;"/>
                </div>-->
                <div class="col-lg-4 m-bot15">
                    <label for="filterCountry">Страна</label>
                    <div class="clearfix"></div>
                    <select id="filterCountry" name="filterCountry"></select>
                </div>
                <div class="col-lg-4 m-bot15">
                    <label for="filterState">Штат/область/регион</label>
                    <div class="clearfix"></div>
                    <select id="filterState" name="filterState" placeholder="-- Все --"></select>
                </div>
                <div class="col-lg-4 m-bot15">
                    <label for="filterCity">Населенный пункт</label>
                    <div class="clearfix"></div>
                    <select id="filterCity" name="filterCity"></select>
                </div>

                <div class="col-lg-12 m-bot15">
                    <input type="submit" value="Найти" class="button transition"/>
                </div>
        </div>
        </div>
    }
</div>
<script>
        $(document).ready(function() {
            $('#filterCountry').on('change', function() {
                $('#filterState').val('-');
                $('#filterState').html('');
                ReloadStates($('#filterCountry').val());
                $('#filterCity').val('-');
                $('#filterCity').html('');
                $('#filterState').select2();
                $('#filterCity').select2();
            });

            $('#filterState').on('change', function() {
                $('#filterCity').val('-');
                $('#filterCity').html('');
                ReloadCities($('#filterState').val());
                $('#filterCity').select2();
            });

            $('#filterCountry').select2();
            $('#filterState').select2();
            $('#filterCity').select2();

            if ($('#DislikeCategory') && $('#DislikeCategory').length > 0 && $('#DislikeCategory').is('select'))
                $('#DislikeCategory').select2();

            AjaxHelper.ajaxRequestJsonData('@Url.Action("GetCountries", "Reference")', null, function(res) {
                $('#filterCountry').append('<option selected value="-">-</option>');
                for (var index = 0; index < res.length; index++) {
                    var item = '<option value="' + res[index].Id + '">' + res[index].Info + '</option>';
                    $('#filterCountry').append(item);
                }
            }, function() {
                alert('Что то пошло не так! сайт временно не доступен попробуйте позднее!');
            }, true);

        });

        function ReloadStates(countryId) {
            $('#filterState').append('<option selected value="-">-</option>');
            AjaxHelper.ajaxRequestJsonData('@Url.Action("GetStates", "Reference")', { countryId: countryId }, function(res) {
                for (var index = 0; index < res.length; index++) {
                    var item = '<option value="' + res[index].Id + '">' + res[index].Info + '</option>';
                    $('#filterState').append(item);
                }
            }, function() {
                alert('Что то пошло не так! сайт временно не доступен попробуйте позднее!');
            }, true);
        }


        function ReloadCities(stateId) {
            $('#filterCity').append('<option selected value="-">-</option>');
            AjaxHelper.ajaxRequestJsonData('@Url.Action("GetCities", "Reference")', { stateId: stateId }, function(res) {
                for (var index = 0; index < res.length; index++) {
                    var item = '<option value="' + res[index].Id + '">' + res[index].Info + '</option>';
                    $('#filterCity').append(item);
                }
            }, function() {
                alert('Что то пошло не так! сайт временно не доступен попробуйте позднее!');
            }, true);
        }
</script>